// packages/@headlessmedia-react/playground/src/App.tsx
import React from 'react'
import { useMedia, useMediaValue } from '@headlessmedia/react'

const mediaID = 'tadatada'

const Child = () => {
  const { currentTime } = useMediaValue({
    id: mediaID,
    selector: mediaContext => mediaContext,
  })
  return <h1>Current time: {currentTime}</h1>
}

const App = () => {
  const { getMediaProps } = useMedia({ id: mediaID })
  return (
    <div>
      <Child />
      <h1>Hello World</h1>
      <video
        onLoadedMetadata={event => {}}
        width={800}
        height={400}
        {...getMediaProps()}
        controls
        src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
      />
    </div>
  )
}

export default App

// packages/@headlessmedia-vue/playground/src/App.vue
<template>
  <Control />
  <video
    width="800"
    height="400"
    controls
    src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
    v-on="mediaEventHanlders"
  />
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { useMedia } from '@headlessmedia/vue'

import Control from './components/Control.vue'

import { mediaId } from './const'

export default defineComponent({
  components: {
    Control,
  },
  name: 'App',
  setup() {
    const { getMediaProps } = useMedia({ id: mediaId })
    const mediaEventHanlders = getMediaProps()

    return { mediaEventHanlders }
  },
})
</script>
